import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { useAIAssistant } from '@/hooks/useAIAssistant';
import { useLearningEntries } from '@/hooks/useLearningEntries';
import { useTopics } from '@/hooks/useTopics';
import { useFavoriteQuestions } from '@/hooks/useFavoriteQuestions';
import { 
  Sparkles, Search, GraduationCap, Lightbulb, Loader2, X, Brain, BookOpen, 
  AlertCircle, ChevronDown, ChevronUp, CheckCircle2, Target, MessageSquare, 
  Zap, Heart, Star, Trash2 
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface AIAssistantPanelProps {
  isOpen: boolean;
  onClose: () => void;
}

interface InterviewQuestion {
  id: number;
  question: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  whyAsked: string;
  sampleAnswer: string;
  keyPoints: string[];
  followUp: string;
}

export function AIAssistantPanel({ isOpen, onClose }: AIAssistantPanelProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [interviewTopic, setInterviewTopic] = useState('');
  const [expandedQuestions, setExpandedQuestions] = useState<Set<number>>(new Set());
  const [activeTab, setActiveTab] = useState('interview');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const { data: entries = [] } = useLearningEntries();
  const { data: topics = [] } = useTopics();
  const { isLoading, response, interviewData, error, smartSearch, getInterviewPrep, getInsights } = useAIAssistant({ entries });
  const { favorites, addFavorite, removeFavorite, isFavorite, getFavoriteId, isLoading: favoritesLoading } = useFavoriteQuestions();

  // Auto-generate interview questions when panel opens and entries exist
  useEffect(() => {
    if (isOpen && entries.length > 0 && !hasAutoGenerated && !interviewData && !isLoading) {
      setHasAutoGenerated(true);
      getInterviewPrep();
    }
  }, [isOpen, entries.length, hasAutoGenerated, interviewData, isLoading]);

  // Reset auto-generate flag when panel closes
  useEffect(() => {
    if (!isOpen) {
      setHasAutoGenerated(false);
    }
  }, [isOpen]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      smartSearch(searchQuery);
    }
  };

  const handleInterviewPrep = (e: React.FormEvent) => {
    e.preventDefault();
    setExpandedQuestions(new Set());
    getInterviewPrep(interviewTopic);
  };

  const handleTopicClick = (topicName: string) => {
    setInterviewTopic(topicName);
    setExpandedQuestions(new Set());
    getInterviewPrep(topicName);
  };

  const toggleQuestion = (id: number) => {
    setExpandedQuestions(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const handleToggleFavorite = (q: InterviewQuestion, sourceTopic?: string) => {
    if (isFavorite(q.question)) {
      const favId = getFavoriteId(q.question);
      if (favId) {
        removeFavorite.mutate(favId);
      }
    } else {
      addFavorite.mutate({
        question: q.question,
        difficulty: q.difficulty,
        category: q.category,
        whyAsked: q.whyAsked,
        sampleAnswer: q.sampleAnswer,
        keyPoints: q.keyPoints,
        followUp: q.followUp,
        sourceTopic: sourceTopic || interviewTopic,
      });
    }
  };

  if (!isOpen) return null;

  const hasEntries = entries.length > 0;

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return 'bg-green-500/10 text-green-600 border-green-500/30';
      case 'medium': return 'bg-amber-500/10 text-amber-600 border-amber-500/30';
      case 'hard': return 'bg-red-500/10 text-red-600 border-red-500/30';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getCategoryIcon = (category: string) => {
    switch (category.toLowerCase()) {
      case 'technical': return <Zap className="w-3 h-3" />;
      case 'behavioral': return <MessageSquare className="w-3 h-3" />;
      case 'system design': return <Target className="w-3 h-3" />;
      default: return <Brain className="w-3 h-3" />;
    }
  };

  const renderQuestionCard = (q: InterviewQuestion, sourceTopic?: string) => {
    const isExpanded = expandedQuestions.has(q.id);
    const favorited = isFavorite(q.question);

    return (
      <Card 
        key={q.id} 
        className="overflow-hidden border-border/50 hover:border-border transition-colors"
      >
        <div
          className="w-full p-4 text-left flex items-start gap-3 cursor-pointer"
          role="button"
          tabIndex={0}
          onClick={() => toggleQuestion(q.id)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              toggleQuestion(q.id);
            }
          }}
        >
          <div className="flex-shrink-0 mt-0.5">
            <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center text-xs font-semibold text-primary">
              {q.id}
            </div>
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-2 flex-wrap">
              <Badge variant="outline" className={`text-[10px] ${getDifficultyColor(q.difficulty)}`}>
                {q.difficulty.toUpperCase()}
              </Badge>
              <Badge variant="outline" className="text-[10px] flex items-center gap-1">
                {getCategoryIcon(q.category)}
                {q.category}
              </Badge>
              {sourceTopic && (
                <Badge variant="secondary" className="text-[10px]">
                  {sourceTopic}
                </Badge>
              )}
            </div>
            <p className="font-medium text-foreground text-sm leading-relaxed">
              {q.question}
            </p>
          </div>
          <div className="flex items-center gap-1 flex-shrink-0">
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              onClick={(e) => {
                e.stopPropagation();
                handleToggleFavorite(q, sourceTopic);
              }}
            >
              <Heart 
                className={`w-4 h-4 transition-colors ${favorited ? 'fill-red-500 text-red-500' : 'text-muted-foreground hover:text-red-500'}`} 
              />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              onClick={(e) => {
                e.stopPropagation();
                toggleQuestion(q.id);
              }}
            >
              {isExpanded ? (
                <ChevronUp className="w-4 h-4 text-muted-foreground" />
              ) : (
                <ChevronDown className="w-4 h-4 text-muted-foreground" />
              )}
            </Button>
          </div>
        </div>
        
        {isExpanded && (
          <div className="px-4 pb-4 pt-0 border-t border-border/50 bg-muted/20">
            <div className="pl-9 space-y-4 pt-4">
              {q.whyAsked && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">
                    Why Interviewers Ask This
                  </p>
                  <p className="text-sm text-foreground/80">{q.whyAsked}</p>
                </div>
              )}
              
              {q.sampleAnswer && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
                    Sample Answer
                  </p>
                  <div className="bg-background/50 rounded-lg p-3 border border-border/50">
                    <p className="text-sm text-foreground/90 leading-relaxed whitespace-pre-line">
                      {q.sampleAnswer}
                    </p>
                  </div>
                </div>
              )}
              
              {q.keyPoints && q.keyPoints.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
                    Key Points to Remember
                  </p>
                  <ul className="space-y-1.5">
                    {q.keyPoints.map((point, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />
                        <span className="text-foreground/80">{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              
              {q.followUp && (
                <div className="bg-amber-500/5 rounded-lg p-3 border border-amber-500/20">
                  <p className="text-xs font-semibold text-amber-600 uppercase tracking-wide mb-1">
                    Possible Follow-up
                  </p>
                  <p className="text-sm text-foreground/80">{q.followUp}</p>
                </div>
              )}
            </div>
          </div>
        )}
      </Card>
    );
  };

  const AIResponseArea = ({ type }: { type: 'search' | 'insights' }) => {
    if (error) {
      return (
        <Card className="p-4 bg-destructive/5 border-destructive/20">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-destructive flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-destructive font-medium text-sm">Something went wrong</p>
              <p className="text-destructive/80 text-sm mt-1">{error}</p>
            </div>
          </div>
        </Card>
      );
    }

    if (isLoading) {
      return (
        <Card className="p-6 bg-secondary/30">
          <div className="flex items-center gap-3 text-muted-foreground">
            <Loader2 className="w-5 h-5 animate-spin" />
            <p>
              {type === 'search' ? 'Searching through your learnings...' : 'Analyzing your learning patterns...'}
            </p>
          </div>
          {response && (
            <div className="mt-4 prose prose-sm max-w-none dark:prose-invert">
              <ReactMarkdown>{response}</ReactMarkdown>
            </div>
          )}
        </Card>
      );
    }

    if (!response) {
      return (
        <Card className="flex-1 flex items-center justify-center p-12 bg-muted/30 border-dashed">
          <div className="text-center text-muted-foreground">
            {type === 'search' ? (
              <>
                <Search className="w-10 h-10 mx-auto mb-3 opacity-50" />
                <p className="text-sm font-medium mb-1">Search your knowledge</p>
                <p className="text-xs">Ask questions about anything you've learned</p>
              </>
            ) : (
              <>
                <Lightbulb className="w-10 h-10 mx-auto mb-3 opacity-50" />
                <p className="text-sm font-medium mb-1">Get personalized insights</p>
                <p className="text-xs">Click the button above to analyze your learning patterns</p>
              </>
            )}
          </div>
        </Card>
      );
    }

    return (
      <ScrollArea className="flex-1">
        <Card className="p-5 bg-secondary/30">
          <div className="prose prose-sm max-w-none dark:prose-invert">
            <ReactMarkdown>{response}</ReactMarkdown>
          </div>
        </Card>
      </ScrollArea>
    );
  };

  return (
    <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm">
      <div className="fixed inset-y-0 right-0 w-full max-w-2xl bg-card border-l border-border shadow-elevated animate-slide-in-right">
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="flex items-center justify-between p-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-primary/10">
                <Brain className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h2 className="font-serif text-lg font-semibold text-foreground">AI Learning Assistant</h2>
                <p className="text-xs text-muted-foreground">
                  {hasEntries ? `Analyzing ${entries.length} learning entries` : 'Add entries to unlock AI features'}
                </p>
              </div>
            </div>
            <Button variant="ghost" size="icon" onClick={onClose}>
              <X className="w-5 h-5" />
            </Button>
          </div>

          {!hasEntries ? (
            <div className="flex-1 flex items-center justify-center p-8">
              <Card className="p-8 text-center max-w-md bg-muted/30 border-dashed">
                <BookOpen className="w-12 h-12 mx-auto mb-4 text-muted-foreground/50" />
                <h3 className="font-semibold text-lg mb-2">No Learning Entries Yet</h3>
                <p className="text-muted-foreground text-sm mb-4">
                  Start adding learning entries to unlock AI-powered search, interview preparation, and insights.
                </p>
                <Button onClick={onClose} variant="outline">
                  Add Your First Entry
                </Button>
              </Card>
            </div>
          ) : (
            <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
              <TabsList className="w-full justify-start rounded-none border-b border-border bg-transparent p-0 h-auto flex-shrink-0">
                <TabsTrigger 
                  value="search" 
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent py-3 px-4"
                >
                  <Search className="w-4 h-4 mr-2" />
                  Smart Search
                </TabsTrigger>
                <TabsTrigger 
                  value="interview" 
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent py-3 px-4"
                >
                  <GraduationCap className="w-4 h-4 mr-2" />
                  Interview Prep
                </TabsTrigger>
                <TabsTrigger 
                  value="favorites" 
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent py-3 px-4"
                >
                  <Star className="w-4 h-4 mr-2" />
                  Favorites
                  {favorites.length > 0 && (
                    <Badge variant="secondary" className="ml-2 text-[10px] h-5">
                      {favorites.length}
                    </Badge>
                  )}
                </TabsTrigger>
                <TabsTrigger 
                  value="insights" 
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent py-3 px-4"
                >
                  <Lightbulb className="w-4 h-4 mr-2" />
                  Insights
                </TabsTrigger>
              </TabsList>

              <div className="flex-1 overflow-hidden">
                {/* Search Tab */}
                <TabsContent value="search" className="h-full m-0 p-4 flex flex-col">
                  <form onSubmit={handleSearch} className="flex gap-2 mb-4 flex-shrink-0">
                    <Input
                      placeholder="Ask anything about your learnings..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="flex-1"
                    />
                    <Button type="submit" disabled={isLoading || !searchQuery.trim()}>
                      {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
                    </Button>
                  </form>
                  <AIResponseArea type="search" />
                </TabsContent>

                {/* Interview Prep Tab */}
                <TabsContent value="interview" className="h-full m-0 flex flex-col overflow-hidden">
                  <div className="p-4 border-b border-border flex-shrink-0 space-y-4">
                    <div>
                      <p className="text-sm text-muted-foreground mb-3">
                        AI generates interview questions with detailed answers based on your learning entries. Filter by topic or search for specific areas.
                      </p>
                      
                      {topics.length > 0 && (
                        <div className="flex flex-wrap gap-2 mb-3">
                          <Button
                            variant={!interviewTopic ? "default" : "outline"}
                            size="sm"
                            onClick={() => {
                              setInterviewTopic('');
                              setExpandedQuestions(new Set());
                              getInterviewPrep();
                            }}
                            disabled={isLoading}
                            className="h-7 text-xs"
                          >
                            All Topics
                          </Button>
                          {topics.map((topic) => (
                            <Button
                              key={topic.id}
                              variant={interviewTopic === topic.name ? "default" : "outline"}
                              size="sm"
                              onClick={() => handleTopicClick(topic.name)}
                              disabled={isLoading}
                              className="h-7 text-xs"
                              style={interviewTopic !== topic.name ? { 
                                borderColor: topic.color || undefined,
                                color: topic.color || undefined
                              } : undefined}
                            >
                              {topic.name}
                            </Button>
                          ))}
                        </div>
                      )}
                      
                      <form onSubmit={handleInterviewPrep} className="flex gap-2">
                        <Input
                          placeholder="Search: React hooks, System design, APIs..."
                          value={interviewTopic}
                          onChange={(e) => setInterviewTopic(e.target.value)}
                          className="flex-1"
                        />
                        <Button type="submit" disabled={isLoading}>
                          {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                          <span className="ml-2">Generate Questions</span>
                        </Button>
                      </form>
                    </div>
                  </div>
                  
                  <ScrollArea className="flex-1">
                    <div className="p-4">
                      {error && (
                        <Card className="p-4 bg-destructive/5 border-destructive/20 mb-4">
                          <div className="flex items-start gap-3">
                            <AlertCircle className="w-5 h-5 text-destructive flex-shrink-0 mt-0.5" />
                            <div>
                              <p className="text-destructive font-medium text-sm">Something went wrong</p>
                              <p className="text-destructive/80 text-sm mt-1">{error}</p>
                              <Button 
                                variant="outline" 
                                size="sm" 
                                className="mt-2"
                                onClick={() => getInterviewPrep(interviewTopic)}
                              >
                                Try Again
                              </Button>
                            </div>
                          </div>
                        </Card>
                      )}
                      
                      {isLoading && (
                        <Card className="p-6 bg-secondary/30">
                          <div className="flex items-center gap-3 text-muted-foreground">
                            <Loader2 className="w-5 h-5 animate-spin" />
                            <div>
                              <p className="font-medium">Generating interview questions...</p>
                              <p className="text-xs">Analyzing your {entries.length} learning entries</p>
                            </div>
                          </div>
                        </Card>
                      )}
                      
                      {interviewData && !isLoading && (
                        <div className="space-y-4">
                          {interviewData.topicsIdentified && interviewData.topicsIdentified.length > 0 && (
                            <div className="flex flex-wrap gap-2 mb-2">
                              <span className="text-xs text-muted-foreground mr-1">Topics covered:</span>
                              {interviewData.topicsIdentified.map((topic, idx) => (
                                <Badge key={idx} variant="secondary" className="text-xs">
                                  {topic}
                                </Badge>
                              ))}
                            </div>
                          )}
                          
                          <div className="space-y-3">
                            {interviewData.questions.map((q) => renderQuestionCard(q, interviewTopic))}
                          </div>
                          
                          {interviewData.studyTips && interviewData.studyTips.length > 0 && (
                            <Card className="p-4 bg-primary/5 border-primary/20">
                              <p className="text-xs font-semibold text-primary uppercase tracking-wide mb-3 flex items-center gap-2">
                                <Sparkles className="w-4 h-4" />
                                Study Tips
                              </p>
                              <ul className="space-y-2">
                                {interviewData.studyTips.map((tip, idx) => (
                                  <li key={idx} className="flex items-start gap-2 text-sm">
                                    <span className="text-primary font-medium">{idx + 1}.</span>
                                    <span className="text-foreground/80">{tip}</span>
                                  </li>
                                ))}
                              </ul>
                            </Card>
                          )}
                        </div>
                      )}
                      
                      {!interviewData && !isLoading && !error && (
                        <Card className="flex items-center justify-center p-12 bg-muted/30 border-dashed">
                          <div className="text-center text-muted-foreground">
                            <GraduationCap className="w-10 h-10 mx-auto mb-3 opacity-50" />
                            <p className="text-sm font-medium mb-1">Ready to practice?</p>
                            <p className="text-xs mb-4">Click a topic above or generate questions for all your learning</p>
                            <Button onClick={() => getInterviewPrep()} size="sm">
                              <Sparkles className="w-4 h-4 mr-2" />
                              Generate Questions
                            </Button>
                          </div>
                        </Card>
                      )}
                    </div>
                  </ScrollArea>
                </TabsContent>

                {/* Favorites Tab */}
                <TabsContent value="favorites" className="h-full m-0 flex flex-col overflow-hidden">
                  <div className="p-4 border-b border-border flex-shrink-0">
                    <p className="text-sm text-muted-foreground">
                      Your saved interview questions for quick reference and practice.
                    </p>
                  </div>
                  
                  <ScrollArea className="flex-1">
                    <div className="p-4">
                      {favoritesLoading ? (
                        <Card className="p-6 bg-secondary/30">
                          <div className="flex items-center gap-3 text-muted-foreground">
                            <Loader2 className="w-5 h-5 animate-spin" />
                            <p>Loading favorites...</p>
                          </div>
                        </Card>
                      ) : favorites.length === 0 ? (
                        <Card className="flex items-center justify-center p-12 bg-muted/30 border-dashed">
                          <div className="text-center text-muted-foreground">
                            <Heart className="w-10 h-10 mx-auto mb-3 opacity-50" />
                            <p className="text-sm font-medium mb-1">No favorites yet</p>
                            <p className="text-xs">Save questions from Interview Prep to access them here</p>
                          </div>
                        </Card>
                      ) : (
                        <div className="space-y-3">
                          {favorites.map((fav, idx) => {
                            const q: InterviewQuestion = {
                              id: idx + 1,
                              question: fav.question,
                              difficulty: fav.difficulty as 'easy' | 'medium' | 'hard',
                              category: fav.category,
                              whyAsked: fav.why_asked || '',
                              sampleAnswer: fav.sample_answer || '',
                              keyPoints: fav.key_points || [],
                              followUp: fav.follow_up || '',
                            };
                            return (
                              <div key={fav.id} className="relative">
                                {renderQuestionCard(q, fav.source_topic || undefined)}
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="absolute top-4 right-14 h-8 w-8 text-muted-foreground hover:text-destructive"
                                  onClick={() => removeFavorite.mutate(fav.id)}
                                >
                                  <Trash2 className="w-4 h-4" />
                                </Button>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  </ScrollArea>
                </TabsContent>

                {/* Insights Tab */}
                <TabsContent value="insights" className="h-full m-0 p-4 flex flex-col">
                  <div className="mb-4 flex-shrink-0">
                    <p className="text-sm text-muted-foreground mb-3">
                      Get AI-powered insights about your learning patterns, knowledge gaps, and suggestions for improvement.
                    </p>
                    <Button onClick={() => getInsights()} disabled={isLoading} className="w-full sm:w-auto">
                      {isLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Lightbulb className="w-4 h-4 mr-2" />}
                      Generate Insights
                    </Button>
                  </div>
                  <AIResponseArea type="insights" />
                </TabsContent>
              </div>
            </Tabs>
          )}
        </div>
      </div>
    </div>
  );
}
